/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorporateLongStayRouteImport } from './routes/corporate-long-stay'
import { Route as GuiaDeAsuncionRouteImport } from './routes/guia-de-asuncion'
import { Route as PropietariosRouteImport } from './routes/propietarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateLongStayRoute = CorporateLongStayRouteImport.update({
  id: '/corporate-long-stay',
  path: '/corporate-long-stay',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDeAsuncionRoute = GuiaDeAsuncionRouteImport.update({
  id: '/guia-de-asuncion',
  path: '/guia-de-asuncion',
  getParentRoute: () => rootRouteImport,
} as any)
const PropietariosRoute = PropietariosRouteImport.update({
  id: '/propietarios',
  path: '/propietarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporate-long-stay': typeof CorporateLongStayRoute
  '/guia-de-asuncion': typeof GuiaDeAsuncionRoute
  '/propietarios': typeof PropietariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporate-long-stay': typeof CorporateLongStayRoute
  '/guia-de-asuncion': typeof GuiaDeAsuncionRoute
  '/propietarios': typeof PropietariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corporate-long-stay': typeof CorporateLongStayRoute
  '/guia-de-asuncion': typeof GuiaDeAsuncionRoute
  '/propietarios': typeof PropietariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/corporate-long-stay' | '/guia-de-asuncion' | '/propietarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corporate-long-stay' | '/guia-de-asuncion' | '/propietarios'
  id:
    | '__root__'
    | '/'
    | '/corporate-long-stay'
    | '/guia-de-asuncion'
    | '/propietarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporateLongStayRoute: typeof CorporateLongStayRoute
  GuiaDeAsuncionRoute: typeof GuiaDeAsuncionRoute
  PropietariosRoute: typeof PropietariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-long-stay': {
      id: '/corporate-long-stay'
      path: '/corporate-long-stay'
      fullPath: '/corporate-long-stay'
      preLoaderRoute: typeof CorporateLongStayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-de-asuncion': {
      id: '/guia-de-asuncion'
      path: '/guia-de-asuncion'
      fullPath: '/guia-de-asuncion'
      preLoaderRoute: typeof GuiaDeAsuncionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propietarios': {
      id: '/propietarios'
      path: '/propietarios'
      fullPath: '/propietarios'
      preLoaderRoute: typeof PropietariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporateLongStayRoute: CorporateLongStayRoute,
  GuiaDeAsuncionRoute: GuiaDeAsuncionRoute,
  PropietariosRoute: PropietariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
